version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: catalog
    ports:
      - "5433:5432"  # host:container (use 5433 on Mac if 5432 is busy)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: api-container
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgre@db:5432/catalog
    ports:
      - "8000:8000"
    

volumes:
  postgres_data: